sudo: false
language: python
cache:
  pip: true
  directories:
    - node_modules
python:
  - "2.7"
  - "3.6"
install:
  - pip install -r requirements.txt
  - python setup.py install
script:
  - python -c 'import pgoapi'
